<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tiny</string>
	</array>
	<key>name</key>
	<string>tinyscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(type|enum|new|if|then|private|native)\b</string>
			<key>name</key>
			<string>keyword.control.tinyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|enum|new|if|else|then|private|native)\b</string>
			<key>name</key>
			<string>keyword.control.tinyscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.tinyscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tinyscript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.tinyscript</string>
				</dict>
			</array>
		</dict>
        <dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.tinyscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.tinyscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.tinyscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tinyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.tinyscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+(\.[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.tinyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z][a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>meta.definition.variable.name.tinyscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tinyscript</string>
	<key>uuid</key>
	<string>795A649F-CB9C-446B-8633-12CF2CB54A0E</string>
</dict>
</plist>
